// Geo Tasks — GET /admin/hrms-geo/task (all tasks; filtered here, as EktaHR does).
// "Task Approvals" = tasks a staff member requested (status "Requested").
import React, { useMemo, useState } from 'react';
import { Button, DatePicker, Descriptions, Dropdown, Input, Modal, Select, Table, Tabs, Typography } from 'antd';
import {
  DownloadOutlined, SearchOutlined, MoreOutlined, EyeOutlined, EnvironmentOutlined, UnorderedListOutlined,
} from '@ant-design/icons';
import dayjs from 'dayjs';
import PageBreadcrumb from '../../components/common/PageBreadcrumb';
import { useGetGeoTasksQuery } from '../../store/api/apiSlice';
import { asText, fmtDate, toList, downloadCsv } from '../Staff/shared/hrUtils';
import { PanelCard, PageHeaderCard, StatusTag, EmptyBlock, LoadError, FiltersButton, FilterField } from '../Staff/shared/StaffUi';
import useSurface from '../Staff/shared/useSurface';
import GeoMap from './shared/GeoMap';
import { latLng, fmtLatLng, mapsLink } from './shared/geoUtils';

const { Text } = Typography;
const { RangePicker } = DatePicker;

const destinationOf = (t) => (t.type === 'Internal' ? t.branch : t.customerName);
const optionsOf = (rows, key) => [...new Set(rows.map((r) => r[key]).filter(Boolean))].sort().map((v) => ({ value: v, label: v }));
const isUrl = (v) => typeof v === 'string' && /^(https?:|data:image\/)/i.test(v);

function TaskDetailModal({ task, onClose }) {
  const pos = latLng(task);
  const markers = useMemo(() => (pos ? [{ id: 't', pos, label: 'T', color: '#B11E6A', title: destinationOf(task) }] : []), [task]); // eslint-disable-line react-hooks/exhaustive-deps
  const circles = useMemo(() => (pos && task?.radius ? [{ id: 'r', pos, radius: task.radius }] : []), [task]); // eslint-disable-line react-hooks/exhaustive-deps
  if (!task) return null;
  const items = [
    ['Task ID', <Text key="id" style={{ fontFamily: 'monospace' }}>{task.id}</Text>],
    ['Title', task.title],
    ['Description', task.description],
    ['Type', task.type],
    [task.type === 'Internal' ? 'Branch' : 'Customer', destinationOf(task)],
    ['Address', task.customerAddress],
    ['Location', pos && <a key="loc" href={mapsLink(pos)} target="_blank" rel="noreferrer">{fmtLatLng(pos)}{task.radius ? ` · ${task.radius} m geofence` : ''}</a>],
    ['Assigned To', [task.staffName, task.staffId].filter(Boolean).join(' · ')],
    ['Assigned By', task.assignedBy],
    ['Status', <StatusTag key="st" status={task.status} />],
    ['Assigned Date', task.assignedDate],
    ['Schedule', [task.startDate, task.endDate].filter(Boolean).join(' → ')],
    ['Time In / Out', [task.timeIn || task.actualFieldInTime, task.timeOut].filter(Boolean).join(' – ')],
    ['Completed', fmtDate(task.completedDate, 'MMM D, YYYY hh:mm A')],
    ['Auto Generated', task.autoGenerated ? 'Yes' : 'No'],
    ['Proof', isUrl(task.proofImg) ? <a key="p" href={task.proofImg} target="_blank" rel="noreferrer">View proof</a> : undefined],
    ...(task.customFields || []).map((f, i) => [asText(f.label || f.name) || `Field ${i + 1}`, asText(f.value ?? f.response)]),
  ].filter(([, v]) => v != null && v !== '').map(([label, children]) => ({ key: label, label, children }));
  return (
    <Modal open onCancel={onClose} footer={null} width={620} title={task.title || 'Task'}>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 12, marginTop: 12 }}>
        {pos && <GeoMap height={200} markers={markers} circles={circles} fitLabel="Recenter" />}
        <Descriptions bordered size="small" column={1} items={items} />
      </div>
    </Modal>
  );
}

export default function GeoTasks() {
  const s = useSurface();
  const [tab, setTab] = useState('list');
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState();
  const [type, setType] = useState();
  const [range, setRange] = useState(null);
  const [selected, setSelected] = useState(null);

  const { data, isFetching, error, refetch } = useGetGeoTasksQuery();
  const tasks = useMemo(() => toList(data), [data]);
  const requested = useMemo(() => tasks.filter((t) => t.status === 'Requested'), [tasks]);

  const rows = useMemo(() => {
    const q = search.trim().toLowerCase();
    return (tab === 'list' ? tasks : requested).filter((t) => (!status || t.status === status)
      && (!type || t.type === type)
      && (!range || (t.assignedDate && !dayjs(t.assignedDate).isBefore(range[0], 'day') && !dayjs(t.assignedDate).isAfter(range[1], 'day')))
      && (!q || [t.id, t.title, t.staffName, t.staffId, destinationOf(t)].some((v) => String(v || '').toLowerCase().includes(q))));
  }, [tab, tasks, requested, search, status, type, range]);

  const actions = (t) => (
    <Dropdown trigger={['click']} menu={{ items: [{ key: 'view', icon: <EyeOutlined />, label: 'View details' }], onClick: ({ domEvent }) => { domEvent.stopPropagation(); setSelected(t); } }}>
      <Button type="text" icon={<MoreOutlined />} onClick={(e) => e.stopPropagation()} />
    </Dropdown>
  );

  const listColumns = [
    { title: 'Task ID', key: 'id', render: (_, t) => <Text style={{ fontFamily: 'monospace', fontSize: 12, fontWeight: 600 }}>{t.id}</Text> },
    {
      title: 'Destination Info', key: 'dest',
      render: (_, t) => <Text strong><EnvironmentOutlined style={{ color: '#d48806', marginRight: 6 }} />{destinationOf(t) || ''}</Text>,
    },
    { title: 'Task Title', key: 'title', render: (_, t) => <Text strong>{t.title}</Text> },
    { title: 'Assigned To', key: 'to', render: (_, t) => t.staffName || '—' },
    { title: 'Assigned By', key: 'by', render: (_, t) => <Text style={{ color: s.muted }}>{t.assignedBy || '—'}</Text> },
    { title: 'Status', key: 'status', render: (_, t) => <StatusTag status={t.status} /> },
    { title: 'Dates', key: 'date', render: (_, t) => <Text style={{ fontFamily: 'monospace', fontSize: 12, color: s.muted }}>{t.assignedDate || '—'}</Text> },
    { title: 'Actions', key: 'actions', align: 'right', width: 70, render: (_, t) => actions(t) },
  ];
  const approvalColumns = [
    { title: 'Emp Name', key: 'name', render: (_, t) => <Text strong>{t.staffName || 'Staff'}</Text> },
    { title: 'Emp ID', key: 'empId', render: (_, t) => <Text style={{ fontFamily: 'monospace', fontSize: 12 }}>{t.staffId || '—'}</Text> },
    { title: 'Customer Name / Branch', key: 'dest', render: (_, t) => destinationOf(t) || '—' },
    { title: 'Task Title', key: 'title', render: (_, t) => <Text strong>{t.title}</Text> },
    { title: 'Date', key: 'date', render: (_, t) => t.assignedDate || '—' },
    { title: 'Status', key: 'status', render: (_, t) => <StatusTag status={t.status} /> },
    { title: 'Actions', key: 'actions', align: 'right', width: 70, render: (_, t) => actions(t) },
  ];

  const exportCsv = () => (tab === 'list'
    ? downloadCsv('geo-tasks.csv', [
      { title: 'Task ID', value: (t) => t.id },
      { title: 'Type', value: (t) => t.type },
      { title: 'Destination (Branch / Customer)', value: destinationOf },
      { title: 'Task Title', value: (t) => t.title },
      { title: 'Assigned To', value: (t) => t.staffName },
      { title: 'Assigned By', value: (t) => t.assignedBy },
      { title: 'Status', value: (t) => t.status },
      { title: 'Assigned Date', value: (t) => t.assignedDate },
      { title: 'Auto Generated', value: (t) => (t.autoGenerated ? 'Yes' : 'No') },
    ], rows)
    : downloadCsv('geo-task-approvals.csv', [
      { title: 'Employee Name', value: (t) => t.staffName },
      { title: 'Employee ID', value: (t) => t.staffId },
      { title: 'Type', value: (t) => t.type },
      { title: 'Customer / Branch', value: destinationOf },
      { title: 'Task Title', value: (t) => t.title },
      { title: 'Date', value: (t) => t.assignedDate },
      { title: 'Status', value: (t) => t.status },
    ], rows));

  const table = error ? <div style={{ padding: 16 }}><LoadError error={error} onRetry={refetch} /></div> : (
    <div className="table-responsive">
      <Table
        className="staff-table"
        size="middle"
        rowKey="_id"
        dataSource={rows}
        columns={tab === 'list' ? listColumns : approvalColumns}
        loading={isFetching}
        onRow={(t) => ({ onClick: () => setSelected(t), style: { cursor: 'pointer' } })}
        pagination={{ defaultPageSize: 10, showSizeChanger: true, showTotal: (t, [a, b]) => `Showing ${a} to ${b} of ${t} entries` }}
        locale={{ emptyText: <EmptyBlock icon={<UnorderedListOutlined />} text={tab === 'list' ? 'No tasks found.' : 'No approval requests found matching.'} /> }}
      />
    </div>
  );

  return (
    <div className="page-container fade-in">
      <PageBreadcrumb items={[{ label: 'HRMS Geo', path: '/hrms-geo' }, { label: 'Tasks' }]} />
      <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
        <PageHeaderCard
          icon={<UnorderedListOutlined />}
          title="Geo Tasks"
          subtitle="Assign task parameters, evaluate employee request logs, and monitor field executions."
          extra={<Button shape="round" icon={<DownloadOutlined />} disabled={!rows.length} onClick={exportCsv}>Export CSV</Button>}
        />
        <Tabs
          activeKey={tab}
          onChange={(k) => { setTab(k); setStatus(undefined); }}
          items={[
            { key: 'list', label: 'Task List Table' },
            { key: 'approvals', label: <span>Task Approvals{requested.length ? ` (${requested.length})` : ''}</span> },
          ]}
          style={{ marginBottom: -8 }}
        />
        <PanelCard bodyStyle={{ padding: 0 }}>
          <div style={{ padding: '12px 16px', display: 'flex', justifyContent: 'space-between', gap: 8, flexWrap: 'wrap', borderBottom: `1px solid ${s.border}` }}>
            <Input
              allowClear
              prefix={<SearchOutlined style={{ color: '#bbb' }} />}
              placeholder={tab === 'list' ? 'Search task ID, title, employee...' : 'Search employee, title...'}
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              style={{ width: 280, maxWidth: '100%', borderRadius: 999 }}
            />
            <FiltersButton count={[status, type, range].filter(Boolean).length} onClear={() => { setStatus(undefined); setType(undefined); setRange(null); }}>
              {tab === 'list' && (
                <FilterField label="Status">
                  <Select allowClear placeholder="All statuses" style={{ width: '100%' }} value={status} onChange={setStatus} options={optionsOf(tasks, 'status')} />
                </FilterField>
              )}
              <FilterField label="Type">
                <Select allowClear placeholder="All types" style={{ width: '100%' }} value={type} onChange={setType} options={[{ value: 'Internal', label: 'Internal' }, { value: 'External', label: 'External' }]} />
              </FilterField>
              <FilterField label="Date Range">
                <RangePicker value={range} onChange={setRange} style={{ width: '100%' }} format="DD MMM YYYY" />
              </FilterField>
            </FiltersButton>
          </div>
          {table}
        </PanelCard>
      </div>
      {selected && <TaskDetailModal task={selected} onClose={() => setSelected(null)} />}
    </div>
  );
}
